### ISSUE TITLE
5.10为啥没编译好的版本了？

### ISSUE THREAD

**Issue by i258559** [UJX6N/bbrplus-5.10#1]
和之前一样，直接替换就行多方便=。=

**Comment by UJX6N** [comment]
> 
> 
> 和之前一样，直接替换就行多方便=。=

刚刚上传😁

**Comment by i258559** [comment]
> > 和之前一样，直接替换就行多方便=。=
> 
> 刚刚上传😁

多谢大佬，更了，哈哈 ^_^

**Comment by liuxyon** [comment]
编译好的ubuntu版本可选的里面是什么内容? 有什么选项?

**Comment by liuxyon** [comment]
安装完重启, 使用lsmod | grep bbrplus  不显示出任何结果, 是不是没有成功?

**Comment by UJX6N** [comment]
> 
> 
> 安装完重启, 使用lsmod | grep bbrplus 不显示出任何结果, 是不是没有成功?

我不是编译成modules的，我是编译进内核了，运行
sysctl net.ipv4.tcp_available_congestion_control
和
sysctl net.ipv4.tcp_congestion_control
看看

**Comment by liuxyon** [comment]
> > 安装完重启, 使用lsmod | grep bbrplus 不显示出任何结果, 是不是没有成功?
> 
> 我不是编译成modules的，我是编译进内核了，运行
> sysctl net.ipv4.tcp_available_congestion_control
> 和
> sysctl net.ipv4.tcp_congestion_control
> 看看

ok, 这个有了, 这个版本是暴力Plus版还是?   晚高峰测试看看.. 主要解决就是丢包没有速度问题...

**Comment by UJX6N** [comment]
> 
> 
> > > 安装完重启, 使用lsmod | grep bbrplus 不显示出任何结果, 是不是没有成功?
> > 
> > 
> > 我不是编译成modules的，我是编译进内核了，运行
> > sysctl net.ipv4.tcp_available_congestion_control
> > 和
> > sysctl net.ipv4.tcp_congestion_control
> > 看看
> 
> ok, 这个有了, 这个版本是暴力Plus版还是? 晚高峰测试看看.. 主要解决就是丢包没有速度问题...

就是
https://github.com/cx9208/bbrplus
的版本，应该不算暴力的吧？我就是移植一下😁

**Comment by liuxyon** [comment]
> > > > 安装完重启，使用lsmod | grep bbrplus不显示出任何结果，是不是没有成功吗？
> > > 
> > > 
> > > 我不是编译成模块的，我是编译进内核了，运行
> > > sysctl net.ipv4.tcp_available_congestion_control
> > > 和
> > > sysctl net.ipv4.tcp_congestion_control
> > > 看看
> > 
> > 
> > 好的，这个有了，这个版本是暴力Plus版还是？晚高峰测试看看..主要解决就是丢包没有速度问题...
> 
> 就是
> https://github.com/cx9208/bbrplus
> 的版本，应该不算暴力的吧？我就是移植一下😁

现在这个时间电信访问youtube又没速度了, 你弄个暴力版的吧？ 一般的没多少效果.

**Comment by UJX6N** [comment]
> 
> 
> > > > > 安装完重启，使用lsmod | grep bbrplus不显示出任何结果，是不是没有成功吗？
> > > > 
> > > > 
> > > > 我不是编译成模块的，我是编译进内核了，运行
> > > > sysctl net.ipv4.tcp_available_congestion_control
> > > > 和
> > > > sysctl net.ipv4.tcp_congestion_control
> > > > 看看
> > > 
> > > 
> > > 好的，这个有了，这个版本是暴力Plus版还是？晚高峰测试看看..主要解决就是丢包没有速度问题...
> > 
> > 
> > 就是
> > https://github.com/cx9208/bbrplus
> > 的版本，应该不算暴力的吧？我就是移植一下😁
> 
> 现在这个时间电信访问youtube又没速度了, 你弄个暴力版的吧？ 一般的没多少效果.

暴力版是哪个？哪里有源码？

**Comment by liuxyon** [comment]
> > > > > > 安装完重启，使用lsmod | grep bbrplus不显示出任何结果，是不是没有成功吗？
> > > > > 
> > > > > 
> > > > > 我不是编译成模块的，我是编译进内核了，运行
> > > > > sysctl net.ipv4.tcp_available_congestion_control
> > > > > 和
> > > > > sysctl net.ipv4.tcp_congestion_control
> > > > > 看看
> > > > 
> > > > 
> > > > 好的，这个有了，这个版本是暴力Plus版还是？晚高峰测试看看..主要解决就是丢包没有速度问题...
> > > 
> > > 
> > > 就是
> > > https://github.com/cx9208/bbrplus
> > > 的版本，应该不算暴力的吧？我就是移植一下😁
> > 
> > 
> > 现在这个时间电信访问youtube又没速度了，你弄个暴力版的吧？一般的没多少效果。
> 
> 暴力版是哪个？哪里有原始码？

我找找看,以前有. 
目前这个版本效果还不如普通的. 不行的.
