### ISSUE TITLE
5.10.12后，debian安装编译好的内核貌似有报错

### ISSUE THREAD

**Issue by i258559** [UJX6N/bbrplus-5.10#2]
Unpacking linux-image-5.10.12-bbrplus (1) ...
Selecting previously unselected package linux-headers-5.10.12-bbrplus.
Preparing to unpack linux-headers-5.10.14-bbrplus.deb ...
Unpacking linux-headers-5.10.12-bbrplus (1) ...
Setting up linux-image-5.10.12-bbrplus (1) ...

 Hmm. There is a symbolic link /lib/modules/5.10.12-bbrplus/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/5.10.12-bbrplus/build

 Hmm. The package shipped with a symbolic link /lib/modules/5.10.12-bbrplus/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/5.10.12-bbrplus/source
--------
不过貌似不影响使用 0.0？

**Comment by UJX6N** [comment]
这不算出错，只是一个提示😁😁😁，其实symbolic link已经由headers包创建了，所以是没问题的

**Comment by UJX6N** [comment]
> 
> 
> Unpacking linux-image-5.10.12-bbrplus (1) ...
> Selecting previously unselected package linux-headers-5.10.12-bbrplus.
> Preparing to unpack linux-headers-5.10.14-bbrplus.deb ...
> Unpacking linux-headers-5.10.12-bbrplus (1) ...
> Setting up linux-image-5.10.12-bbrplus (1) ...
> 
> Hmm. There is a symbolic link /lib/modules/5.10.12-bbrplus/build
> However, I can not read it: No such file or directory
> Therefore, I am deleting /lib/modules/5.10.12-bbrplus/build
> ## Hmm. The package shipped with a symbolic link /lib/modules/5.10.12-bbrplus/source
> However, I can not read the target: No such file or directory
> Therefore, I am deleting /lib/modules/5.10.12-bbrplus/source
> 
> 不过貌似不影响使用 0.0？

最新的5.10.16版本里应该解决这提示的问题了

**Comment by i258559** [comment]
5.10.16确实是没这个提示了 =V=
年后第一天，新年快乐～ @v@

**Comment by liuxyon** [comment]
kernel 目前所有版本都存在BUG, 我已经提交了报告,他们正在修复中,预计17以后下个版本可能修复
