### ISSUE TITLE
its based on ?

### ISSUE THREAD

**Issue by UntaDotMy** [UJX6N/bbrplus-5.10#3]
im sorry , i need to ask , it based on 4.14,129 or 4.14,182 version of bbrplus ?

can you make one for 4.14-129 ? tq

**Comment by UJX6N** [comment]
> 
> 
> im sorry , i need to ask , it based on 4.14,129 or 4.14,182 version of bbrplus ?
> 
> can you make one for 4.14-129 ? tq

cant find version 182 anywhere (everybody deleted it from their repositories), so i dont know what issue it got.

my project based on 
https://github.com/cx9208/bbrplus

however, i integrated some patches of tha official BBR so i cant guarantee better or worse than tha original BBRPLUS.

**Comment by UntaDotMy** [comment]
> > im sorry , i need to ask , it based on 4.14,129 or 4.14,182 version of bbrplus ?
> > can you make one for 4.14-129 ? tq
> 
> cant find version 182 anywhere (everybody deleted it from their repositories), so i dont know what issue it got.
> 
> my project based on
> https://github.com/cx9208/bbrplus
> 
> however, i integrated some patches of tha official BBR so i cant guarantee better or worse than tha original BBRPLUS.

so this project is based on 4.14.129 ? tq for reply , im using your kernel now , and yea , awesome .

**Comment by UntaDotMy** [comment]
> > im sorry , i need to ask , it based on 4.14,129 or 4.14,182 version of bbrplus ?
> > can you make one for 4.14-129 ? tq
> 
> cant find version 182 anywhere (everybody deleted it from their repositories), so i dont know what issue it got.
> 
> my project based on
> https://github.com/cx9208/bbrplus
> 
> however, i integrated some patches of tha official BBR so i cant guarantee better or worse than tha original BBRPLUS.

this is 182 ver . can u compile ?

header -https://chinagz2018-my.sharepoint.com/:u:/g/personal/ylx_chinagz2018_onmicrosoft_com/Ef9pJn1wp-pBk4FIPxT1qBoBqpWhTVCawoKzEB0_vpiMRw?download=1

image - https://chinagz2018-my.sharepoint.com/:u:/g/personal/ylx_chinagz2018_onmicrosoft_com/EaFJshr8za9Bq9FGjEBLds0B4ZfrYThLH8E35xe9-qWX_Q?download=1

**Comment by UJX6N** [comment]
> 
> 
> > > im sorry , i need to ask , it based on 4.14,129 or 4.14,182 version of bbrplus ?
> > > can you make one for 4.14-129 ? tq
> > 
> > 
> > cant find version 182 anywhere (everybody deleted it from their repositories), so i dont know what issue it got.
> > my project based on
> > https://github.com/cx9208/bbrplus
> > however, i integrated some patches of tha official BBR so i cant guarantee better or worse than tha original BBRPLUS.
> 
> this is 182 ver . can u compile ?
> 
> header -https://chinagz2018-my.sharepoint.com/:u:/g/personal/ylx_chinagz2018_onmicrosoft_com/Ef9pJn1wp-pBk4FIPxT1qBoBqpWhTVCawoKzEB0_vpiMRw?download=1
> 
> image - https://chinagz2018-my.sharepoint.com/:u:/g/personal/ylx_chinagz2018_onmicrosoft_com/EaFJshr8za9Bq9FGjEBLds0B4ZfrYThLH8E35xe9-qWX_Q?download=1

i cant coz source not included. but i check it out and confirm this ver was not built by me. 🧐
