### ISSUE TITLE
Centos 8 Racknerd VPS 和 ubuntu20.04 安装后5.10 无法启动

### ISSUE THREAD

**Issue by jinwyp** [UJX6N/bbrplus-5.10#5]
全新的 Centos 8 Racknerd VPS

直接安装手动 安装后无法启动 

在本地 ubuntu20.04 安装内核 5.10 bbr plus 也无法启动

可以用我做的脚本测试 安装过程中都选了删除原来内核

如果不选择删除内核 可以正常启动

https://github.com/jinwyp/one_click_script/issues/62

**Comment by tanpengsccd** [comment]
```
Setting up dkms (2.8.1-5ubuntu2) ...
Setting up wireguard-dkms (1.0.20201112-1~20.04.1) ...
Loading new wireguard-1.0.20201112 DKMS files...
Building for 5.10.27-bbrplus
Building initial module for 5.10.27-bbrplus
Error!  The /var/lib/dkms/wireguard/1.0.20201112/5.10.27-bbrplus/x86_64/dkms.conf for module wireguard includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
Skipped.
Setting up wireguard (1.0.20200513-1~20.04.2) ...
Processing triggers for man-db (2.9.1-1) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
wireguard-tools is already the newest version (1.0.20200513-1~20.04.2).
wireguard-tools set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
ln: failed to create symbolic link '/usr/local/bin/resolvconf': File exists

 ==================================================
 开始安装 Cloudflare Warp 命令行工具 Wgcf
.......
```



ubuntu20.04 安装bbr plus 5.10 内核后 再安装wg 出错

**Comment by jinwyp** [comment]
> ```
> Setting up dkms (2.8.1-5ubuntu2) ...
> Setting up wireguard-dkms (1.0.20201112-1~20.04.1) ...
> Loading new wireguard-1.0.20201112 DKMS files...
> Building for 5.10.27-bbrplus
> Building initial module for 5.10.27-bbrplus
> Error!  The /var/lib/dkms/wireguard/1.0.20201112/5.10.27-bbrplus/x86_64/dkms.conf for module wireguard includes a BUILD_EXCLUSIVE directive which
> does not match this kernel/arch.  This indicates that it should not be built.
> Skipped.
> Setting up wireguard (1.0.20200513-1~20.04.2) ...
> Processing triggers for man-db (2.9.1-1) ...
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> wireguard-tools is already the newest version (1.0.20200513-1~20.04.2).
> wireguard-tools set to manually installed.
> 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
> ln: failed to create symbolic link '/usr/local/bin/resolvconf': File exists
> 
>  ==================================================
>  开始安装 Cloudflare Warp 命令行工具 Wgcf
> .......
> ```
> 
> ubuntu20.04 安装bbr plus 5.10 内核后 再安装wg 出错

这个不是内核问题 请到我的项目 提问, 我已经修改了脚本 你可以在试一下

**Comment by UJX6N** [comment]
> 
> 
> 全新的 Centos 8 Racknerd VPS
> 
> 直接安装手动 安装后无法启动
> 
> 在本地 ubuntu20.04 安装内核 5.10 bbr plus 也无法启动
> 
> 可以用我做的脚本测试 安装过程中都选了删除原来内核
> 
> 如果不选择删除内核 可以正常启动
> 
> [jinwyp/one_click_script#62](https://github.com/jinwyp/one_click_script/issues/62)

centos、ubuntu如果都不删除原来的内核，可以启动吗？

不能启动的话，有
console截屏
或dmesg信息（可能在 `/var/log/dmesg` ）
或journalctl信息（通过命令如 `journalctl -t kernel` ）
可以看吗？

P.S. 我有空再测下你的脚本

**Comment by jinwyp** [comment]
> > 全新的 Centos 8 Racknerd VPS
> > 直接安装手动 安装后无法启动
> > 在本地 ubuntu20.04 安装内核 5.10 bbr plus 也无法启动
> > 可以用我做的脚本测试 安装过程中都选了删除原来内核
> > 如果不选择删除内核 可以正常启动
> > [jinwyp/one_click_script#62](https://github.com/jinwyp/one_click_script/issues/62)
> 
> centos、ubuntu如果都不删除原来的内核，可以启动吗？
> 
> 不能启动的话，有
> console截屏
> 或dmesg信息（可能在 `/var/log/dmesg` ）
> 或journalctl信息（通过命令如 `journalctl -t kernel` ）
> 可以看吗？
> 
> P.S. 我有空再测下你的脚本

用了最新的 5.10.28 centos 7 和 8  没问题了, 删除原来内核也正常了. 

ubuntu 删除内核 弹出的大框 说要更新grub  选择更新就无法启动了, 
是运行 apt -y --purge autoremove 导致的. 如果不运行 apt -y --purge autoremove  就没问题 

不删除老内核内核 是没有问题 可以正常启动.    即使删除了内核 例如header 也是没问题的. 

删除旧module内核 会导致依赖 删除 image 内核,  ,  即使安装了新内核 而如果用 apt -y --purge autoremove 运行一下就会导致更新 grub 出现无法启动.   不运行 apt -y --purge autoremove 就没问题. 
还有你的编译的模块 没有像 官方带有 module 内核文件

**Comment by UJX6N** [comment]
你的脚本我还没看过，purge之后，再运行一次
`update-grub`
或
`update-grub2`
呢？

关于module，我是按debian内核编译的，debian没有单独的module，都包含在image里。

ubuntu的内核才有module，但ubuntu装debian内核也不需要module的。在debian内核上编译mod也不需要module包。主要是ubuntu跟debian的分包有差别，但内容其实是一样的。
